FROM python:3.10.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
RUN pip install pipenv

COPY ./deploy/scripts/entrypoint.py /entrypoint.py
COPY Pipfile Pipfile.lock ./

RUN pipenv install --system --dev

COPY ./app .

ENTRYPOINT [ "/entrypoint.py" ]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]